# Generated by Django 2.1.5 on 2019-01-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginmodule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='avatar',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
