# Generated by Django 2.1.5 on 2019-02-05 05:51
#This template has been copied from the output migration file generated by "python3 src/chatproject/manage.py makemigrations loginmodule --empty" command.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #0002_login_avatar is the previous migration file name.Check loginmodule/migrations directory content
        ('loginmodule', '0002_login_avatar'),
    ]

    def insertData(apps, schema_editor):
     #First clear all entries if any.
     Login = apps.get_model('loginmodule', 'Login')
     Login.objects.all().delete()
     user = Login(name = "admin", login_id = "admin", password = "password", email = "admin@pychat.com", type = "Admin", avatar="admin.jpg")
     user.save()
     user = Login(name = "Nisha Singh", login_id = "nisha", password = "password", email = "nisha@pychat.com", type = "User", avatar="nishasingh.jpg")
     user.save()
     user = Login(name = "Mark Mackron", login_id = "mark", password = "password", email = "mark@pychat.com", type = "User", avatar="markmackron.jpg")
     user.save()
     user = Login(name = "Rose White", login_id = "rose", password = "password", email = "rose@pychat.com", type = "User", avatar="rosewhite.jpg")
     user.save()
     user = Login(name = "Yug Bhatia", login_id = "yug", password = "password", email = "yug@pychat.com", type = "User", avatar="yug.jpg")
     user.save()

    operations = [
        migrations.RunPython(insertData),
    ]
